export const routeNames = {
  Home: '/',
  About: '/about',
  Contact: '/contact',
  NotFound: '/not-found',
  SignIn: '/auth/sign-in',
  Houses: '/houses',
  Reservation: '/reservation/:house_id',
  Payment: '/payments/:id',
  DetailHouse: '/houses/:house_id',
  OrderSuccess: '/orders',
  UserDashboard: '/user-dashboard/:user_id',
  ReportLivingIssues: '/living-issues',
  Support: '/support',
  Management: '/management',
  ExtraServices: '/extra-services',
  ContactUs: '/contact-us',
  PaymentHistory: 'payment-history',
  EditUserInfo: '/edit-user-info',
  ChangePassword: '/change-password',
  Wishlist: '/wishlist',
};
