export const routeNames = {
  Home: '/',
  About: '/about',
  Contact: '/contact',
  NotFound: '/not-found',
  SignIn: '/auth/sign-in',
  Houses: '/houses',
  Reservation: '/reservation/:house_id',
  Payment: '/reservation/:house_id/payments',
  DetailHouse: '/houses/:house_id',
  OrderSuccess: '/payments/:order_id',
  UserDashboard: '/user-dashboard/:user_id',
  ReportLivingIssues: '/living-issues',
  ExtraServices: '/extra-services',
};
